### ISSUE TITLE
Length of a tokens not matched number of the graph nodes

### ISSUE THREAD

**Issue by KESHEN-ZHOU** [sosppxo/RG-SAN#5]
The error is indicated below, so there is a mismatch between the tokens and the graph node.
Within the get_graph_filesnames() in scannetv2.py, I have changed the following one line of code otherwise it won't compile
from: 
`token_id += tokenizer.encode(words, add_special_tokens=False)`
to:
`token_id += tokenizer.encode(words, is_split_into_words=True, add_special_tokens=False)`
I am using the Pretrained Mpnet-base from the Huggingface.  
Any suggestions to solve this issue? Thanks

```
loading train graphs...
  0%|                                                                                                                              | 0/70657 [00:00<?, ?it/s]before: token_id is token_id [30527]
after: len of token_id is 15
after: token_id is [30527, 2027, 2007, 1041, 2150, 2799, 1016, 2013, 2007, 5311, 2180, 3351, 14712, 2019, 1016]
14
Mismatch: len(token_id)=15, g.num_nodes()=14
Words: ['this', 'is', 'a', 'long', 'table', '.', 'it', 'is', 'facing', 'four', 'bar', 'stools', '.']
Tails: [ 5  1  2  3  4  6  9  7  8 10 11 12 13], Heads: [ 0  5  5  5  5  5  0  9  9 12 12  9  9]
  0%|                                                                                                                              | 0/70657 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/train.py", line 256, in <module>
    gorilla.launch(
  File "/home/kzho6770/miniconda3/envs/rg-san/lib/python3.8/site-packages/gorilla/core/launch.py", line 68, in launch
    main_func(*args)
  File "tools/train.py", line 230, in main
    train_dataset = build_dataset(cfg.data.train, logger)
  File "/home/kzho6770/Project/my/work/RG-SAN/rg_san/dataset/__init__.py", line 15, in build_dataset
    return ScanNetDataset_sample_graph_edge(**_data_cfg)
  File "/home/kzho6770/Project/my/work/RG-SAN/rg_san/dataset/scannetv2.py", line 83, in __init__
    self.filenames = self.get_graph_filenames()
  File "/home/kzho6770/Project/my/work/RG-SAN/rg_san/dataset/scannetv2.py", line 224, in get_graph_filenames
    raise AssertionError("Number of tokens does not match number of graph nodes")
AssertionError: Number of tokens does not match number of graph nodes
```

**Comment by sosppxo** [comment]
Hi, thanks for the feedback! We have fix this issue and update the part of saving dgl files, please try again.
