### ISSUE TITLE
"TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]"

### ISSUE THREAD

**Issue by fhcbvdjknl** [sosppxo/RG-SAN#6]
The error is indicated below，any suggestions to solve this issue? Thanks

(rg-san) root@autodl-container-f1cc40b633-ea23fdd8:~/autodl-tmp/RG-SAN# bash scripts/test.sh
Using backend: pytorch
/root/miniconda3/envs/rg-san/lib/python3.8/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
set CUDA_VISIBLE_DEVICES as 0
Some weights of MPNetModel were not initialized from the model checkpoint at ./backbones/mpnet-base and are newly initialized: ['mpnet.pooler.dense.bias', 'mpnet.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2024-12-22 18:56:43,101 - INFO - Load state dict from checkpoint/best.pth
2024-12-22 18:56:45,033 - WARNING - The model and loaded state dict do not match exactly

size mismatch for criterion.loss_weight: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([4]).
unexpected key in source state_dict: text_encoder.embeddings.position_ids

loading val graphs...
  0%|                                                                                                                                        | 0/9508 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/test.py", line 121, in <module>
    main()
  File "tools/test.py", line 34, in main
    dataset = build_dataset(cfg.data.val, logger)
  File "/root/autodl-tmp/RG-SAN/rg_san/dataset/__init__.py", line 15, in build_dataset
    return ScanNetDataset_sample_graph_edge(**_data_cfg)
  File "/root/autodl-tmp/RG-SAN/rg_san/dataset/scannetv2.py", line 83, in __init__
    self.filenames = self.get_graph_filenames()
  File "/root/autodl-tmp/RG-SAN/rg_san/dataset/scannetv2.py", line 211, in get_graph_filenames
    token_id += tokenizer.encode(words, add_special_tokens=False)
  File "/root/miniconda3/envs/rg-san/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2348, in encode
    encoded_inputs = self.encode_plus(
  File "/root/miniconda3/envs/rg-san/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2756, in encode_plus
    return self._encode_plus(
  File "/root/miniconda3/envs/rg-san/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 497, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "/root/miniconda3/envs/rg-san/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 425, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

**Comment by sosppxo** [comment]
Hi, it's the same issue as #5 , and we have fix it by updating the file, please try again~
